#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
dry="0"

while [[ $# > 0 ]]; do 
	if [[ $1 == "--dry" ]]; then
		dry="1"
	fi
	shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry == "1" ]]; then
        return
    fi
    "$@"
}

log "--------------- dev-env ---------------"

stow_dir() {
    pushd $1

    dirs=$(find . -maxdepth 1 -mindepth 1 -type d)
    for dir in $dirs; do
        execute stow -d . -t ~/ -D ${dir:2}
        execute stow -d . -t ~/ -R ${dir:2}
    done

    popd
}

stow_dir ~/dotfiles/config
