#!/usr/bin/env bash

rm -rf $HOME/personal/neovim
git clone https://github.com/neovim/neovim.git $HOME/personal/neovim
cd $HOME/personal/neovim

sudo apt install cmake gettext lua5.3 liblua5.1-0-dev
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

